spring.application.name=connections-service
eureka.client.service-url.defaultZone= http://localhost:8761/eureka

spring.neo4j.uri=bolt://localhost:7690
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=sai2714@

# Optional but useful
spring.neo4j.database=neo4j
spring.neo4j.connection-timeout=30s
spring.neo4j.max-transaction-retry-time=15s
