server.port: 8080

eureka.client.service-url.defaultZone: http://localhost:8761/eureka


#secretKey should be 32 chars
jwt.secretKey: w0xX1Z+3XnH0Z4Vnq8p8Q2g8RZQ8bqQm8ZlqZcYv6ZQ=

spring:

  application.name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: ${USER-SERVICE_URI:lb://USER-SERVICE}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: ${POSTS-SERVICE_URI:lb://POSTS-SERVICE}
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: connections-service
          uri: ${CONNECTIONS-SERVICE_URI:lb://CONNECTIONS-SERVICE}
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter



