server:
  port: 9020
  servlet:
    context-path: /posts

spring:
  multipart:
    enabled: true
    max-file-size: 20MB
    max-request-size: 20MB
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    properties:
#      spring.json.add.type.headers: false
