spring.application.name=uploader-service

eureka.client.service-url.defaultZone= http://localhost:8761/eureka

cloudinary.cloud-name = da4hbrpgt
cloudinary.api-key= 741892882834845
cloudinary.api-secret= Pn134YpPHJTxWdL1n3S0yj4Rfd4
